# Generated by Django 5.2.1 on 2025-05-21 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatIntelligenceFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Feed Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('feed_type', models.CharField(choices=[('misp', 'MISP'), ('otx', 'AlienVault OTX'), ('threatfox', 'ThreatFox'), ('virustotal', 'VirusTotal'), ('custom', 'Custom Feed')], max_length=50, verbose_name='Feed Type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('pending', 'Pending Configuration')], default='pending', max_length=20, verbose_name='Status')),
                ('is_public', models.BooleanField(default=False, help_text='If checked, this feed will be available to all organizations', verbose_name='Public Feed')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Last Synchronization')),
                ('sync_frequency', models.IntegerField(default=60, verbose_name='Sync Frequency (minutes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat_feeds', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Threat Intelligence Feed',
                'verbose_name_plural': 'Threat Intelligence Feeds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MISPInstance',
            fields=[
                ('threatintelligencefeed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vision.threatintelligencefeed')),
                ('url', models.URLField(help_text='URL of the MISP instance', verbose_name='MISP URL')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key')),
                ('verify_ssl', models.BooleanField(default=True, verbose_name='Verify SSL')),
                ('import_events', models.BooleanField(default=True, verbose_name='Import Events')),
                ('import_attributes', models.BooleanField(default=True, verbose_name='Import Attributes')),
                ('import_from_days', models.IntegerField(default=30, verbose_name='Import from last X days')),
                ('tags_to_include', models.TextField(blank=True, help_text='Comma-separated list of tags to include', verbose_name='Tags to Include')),
                ('tags_to_exclude', models.TextField(blank=True, help_text='Comma-separated list of tags to exclude', verbose_name='Tags to Exclude')),
            ],
            options={
                'verbose_name': 'MISP Instance',
                'verbose_name_plural': 'MISP Instances',
            },
            bases=('vision.threatintelligencefeed',),
        ),
        migrations.CreateModel(
            name='ThreatIntelligenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('ip', 'IP Address'), ('domain', 'Domain'), ('url', 'URL'), ('hash', 'File Hash'), ('email', 'Email'), ('event', 'Event'), ('other', 'Other')], max_length=50, verbose_name='Item Type')),
                ('value', models.TextField(verbose_name='Value')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='First Seen')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Last Seen')),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10, verbose_name='Confidence')),
                ('is_malicious', models.BooleanField(default=False, verbose_name='Is Malicious')),
                ('tlp', models.CharField(choices=[('white', 'TLP:WHITE'), ('green', 'TLP:GREEN'), ('amber', 'TLP:AMBER'), ('red', 'TLP:RED')], default='amber', max_length=10, verbose_name='TLP')),
                ('tags', models.TextField(blank=True, help_text='Comma-separated list of tags', verbose_name='Tags')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('external_id', models.CharField(blank=True, help_text='ID in the original source system', max_length=255, verbose_name='External ID')),
                ('external_url', models.URLField(blank=True, help_text='URL to the item in the source system', verbose_name='External URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intel_items', to='vision.threatintelligencefeed', verbose_name='Feed Source')),
            ],
            options={
                'verbose_name': 'Threat Intelligence Item',
                'verbose_name_plural': 'Threat Intelligence Items',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['value'], name='vision_thre_value_ddb16b_idx'), models.Index(fields=['item_type'], name='vision_thre_item_ty_4504ca_idx')],
                'constraints': [models.UniqueConstraint(fields=('feed', 'item_type', 'value', 'external_id'), name='unique_intel_item')],
            },
        ),
    ]
