# Generated by Django 5.2.1 on 2025-05-21 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mispinstance',
            name='import_galaxies',
            field=models.BooleanField(default=False, help_text='Import all galaxy and cluster definitions from MISP', verbose_name='Import Galaxies/Clusters'),
        ),
        migrations.AddField(
            model_name='mispinstance',
            name='import_tags',
            field=models.BooleanField(default=False, help_text='Import all tag definitions from MISP', verbose_name='Import Tags'),
        ),
        migrations.CreateModel(
            name='MISPGalaxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, verbose_name='External ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('type', models.CharField(max_length=255, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misp_galaxies', to='vision.mispinstance', verbose_name='MISP Instance')),
            ],
            options={
                'verbose_name': 'MISP Galaxy',
                'verbose_name_plural': 'MISP Galaxies',
                'ordering': ['name'],
                'unique_together': {('feed', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='MISPCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, verbose_name='External ID')),
                ('uuid', models.CharField(blank=True, max_length=255, verbose_name='UUID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('source', models.CharField(blank=True, max_length=255, verbose_name='Source')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('galaxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='vision.mispgalaxy', verbose_name='MISP Galaxy')),
            ],
            options={
                'verbose_name': 'MISP Cluster',
                'verbose_name_plural': 'MISP Clusters',
                'ordering': ['value'],
                'unique_together': {('galaxy', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='MISPTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tag Name')),
                ('colour', models.CharField(blank=True, max_length=7, verbose_name='Colour')),
                ('external_id', models.CharField(max_length=255, verbose_name='External ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Is Hidden')),
                ('is_system', models.BooleanField(default=False, verbose_name='Is System Tag')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misp_tags', to='vision.mispinstance', verbose_name='MISP Instance')),
            ],
            options={
                'verbose_name': 'MISP Tag',
                'verbose_name_plural': 'MISP Tags',
                'ordering': ['name'],
                'unique_together': {('feed', 'external_id')},
            },
        ),
    ]
