# Generated by Django 5.2.1 on 2025-05-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0002_mispinstance_import_galaxies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatintelligenceitem',
            name='attribute_count',
            field=models.IntegerField(default=0, verbose_name='Number of Attributes'),
        ),
        migrations.AddField(
            model_name='threatintelligenceitem',
            name='correlation_count',
            field=models.IntegerField(default=0, verbose_name='Number of Correlations'),
        ),
        migrations.AddField(
            model_name='threatintelligenceitem',
            name='creator_org',
            field=models.CharField(blank=True, max_length=255, verbose_name='Creator Organization'),
        ),
        migrations.AddField(
            model_name='threatintelligenceitem',
            name='creator_user',
            field=models.CharField(blank=True, max_length=255, verbose_name='Creator User'),
        ),
        migrations.AddField(
            model_name='threatintelligenceitem',
            name='distribution',
            field=models.CharField(blank=True, max_length=50, verbose_name='Distribution'),
        ),
        migrations.AddField(
            model_name='threatintelligenceitem',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Event Date'),
        ),
        migrations.AddField(
            model_name='threatintelligenceitem',
            name='owner_org',
            field=models.CharField(blank=True, max_length=255, verbose_name='Owner Organization'),
        ),
    ]
