[pytest]
DJANGO_SETTINGS_MODULE = sentineliq.settings
python_files = test_*.py *_test.py tests.py
testpaths = ./
filterwarnings =
    ignore::DeprecationWarning
    ignore::django.utils.deprecation.RemovedInDjango61Warning 