# Generated by Django 5.2.1 on 2025-05-21 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('color', models.CharField(choices=[('primary', 'Blue'), ('secondary', 'Gray'), ('success', 'Green'), ('danger', 'Red'), ('warning', 'Yellow'), ('info', 'Light Blue'), ('light', 'White'), ('dark', 'Black')], default='primary', max_length=20, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Observable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('type', models.CharField(choices=[('ip', 'IP Address'), ('domain', 'Domain'), ('url', 'URL'), ('email', 'Email'), ('hash_md5', 'MD5 Hash'), ('hash_sha1', 'SHA1 Hash'), ('hash_sha256', 'SHA256 Hash'), ('filename', 'Filename'), ('filepath', 'Filepath'), ('registry', 'Registry'), ('user_agent', 'User Agent'), ('process', 'Process'), ('cve', 'CVE'), ('other', 'Other')], max_length=20, verbose_name='Type')),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10, verbose_name='Confidence')),
                ('malicious', models.BooleanField(default=False, verbose_name='Malicious')),
                ('pap', models.CharField(choices=[('unknown', 'Unknown (PAP:UNKNOWN)'), ('white', 'White (PAP:WHITE)'), ('green', 'Green (PAP:GREEN)'), ('amber', 'Amber (PAP:AMBER)'), ('red', 'Red (PAP:RED)')], default='unknown', help_text='Permissible Actions Protocol: Defines how this observable can be shared or used.', max_length=10, verbose_name='PAP Level')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observables', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Observable',
                'verbose_name_plural': 'Observables',
                'ordering': ['-updated_at'],
                'unique_together': {('value', 'type')},
            },
        ),
    ]
