# Generated by Django 5.2.1 on 2025-05-21 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MitreTactic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tactic_id', models.CharField(max_length=50, unique=True, verbose_name='Tactic ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'MITRE Tactic',
                'verbose_name_plural': 'MITRE Tactics',
                'ordering': ['tactic_id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('color', models.CharField(choices=[('primary', 'Blue'), ('secondary', 'Gray'), ('success', 'Green'), ('danger', 'Red'), ('warning', 'Yellow'), ('info', 'Light Blue'), ('light', 'White'), ('dark', 'Black')], default='primary', max_length=20, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MitreTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique_id', models.CharField(max_length=50, unique=True, verbose_name='Technique ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('tactics', models.ManyToManyField(related_name='techniques', to='core.mitretactic')),
            ],
            options={
                'verbose_name': 'MITRE Technique',
                'verbose_name_plural': 'MITRE Techniques',
                'ordering': ['technique_id'],
            },
        ),
        migrations.CreateModel(
            name='MitreSubTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_technique_id', models.CharField(max_length=50, unique=True, verbose_name='Sub-technique ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('parent_technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtechniques', to='core.mitretechnique')),
            ],
            options={
                'verbose_name': 'MITRE Sub-technique',
                'verbose_name_plural': 'MITRE Sub-techniques',
                'ordering': ['sub_technique_id'],
            },
        ),
        migrations.CreateModel(
            name='MitreAttackGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitre_attack_groups', to='organizations.organization', verbose_name='Organização')),
                ('subtechniques', models.ManyToManyField(blank=True, related_name='attack_groups', to='core.mitresubtechnique', verbose_name='Sub-técnicas')),
                ('tactics', models.ManyToManyField(blank=True, related_name='attack_groups', to='core.mitretactic', verbose_name='Táticas')),
                ('techniques', models.ManyToManyField(blank=True, related_name='attack_groups', to='core.mitretechnique', verbose_name='Técnicas')),
            ],
            options={
                'verbose_name': 'Grupo MITRE ATT&CK',
                'verbose_name_plural': 'Grupos MITRE ATT&CK',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Observable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('type', models.CharField(choices=[('ip', 'IP Address'), ('domain', 'Domain'), ('url', 'URL'), ('email', 'Email'), ('hash_md5', 'MD5 Hash'), ('hash_sha1', 'SHA1 Hash'), ('hash_sha256', 'SHA256 Hash'), ('filename', 'Filename'), ('filepath', 'Filepath'), ('registry', 'Registry'), ('user_agent', 'User Agent'), ('process', 'Process'), ('cve', 'CVE'), ('other', 'Other')], max_length=20, verbose_name='Type')),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10, verbose_name='Confidence')),
                ('is_malicious', models.BooleanField(default=False, verbose_name='Malicious')),
                ('pap', models.CharField(choices=[('unknown', 'Unknown (PAP:UNKNOWN)'), ('white', 'White (PAP:WHITE)'), ('green', 'Green (PAP:GREEN)'), ('amber', 'Amber (PAP:AMBER)'), ('red', 'Red (PAP:RED)')], default='unknown', help_text='Permissible Actions Protocol: Defines how this observable can be shared or used.', max_length=10, verbose_name='PAP Level')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Last Seen')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observables', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Observable',
                'verbose_name_plural': 'Observables',
                'ordering': ['-updated_at'],
            },
        ),
    ]
