# Generated by Django 5.2.1 on 2025-05-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('primary', 'Blue'), ('secondary', 'Gray'), ('success', 'Green'), ('danger', 'Red'), ('warning', 'Yellow'), ('info', 'Light Blue'), ('light', 'White'), ('dark', 'Black')], default='primary', max_length=20, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='Observable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('type', models.CharField(choices=[('ip_address', 'IP Address'), ('domain', 'Domain'), ('url', 'URL'), ('email', 'Email'), ('hash_md5', 'MD5 Hash'), ('hash_sha1', 'SHA1 Hash'), ('hash_sha256', 'SHA256 Hash'), ('filename', 'Filename'), ('registry_key', 'Registry Key'), ('user_agent', 'User Agent'), ('process_name', 'Process Name'), ('mutex', 'Mutex'), ('cve', 'CVE'), ('other', 'Other')], default='other', max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10, verbose_name='Confidence')),
                ('is_malicious', models.BooleanField(default=False, verbose_name='Is Malicious')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='First Seen')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Last Seen')),
            ],
            options={
                'verbose_name': 'Observable',
                'verbose_name_plural': 'Observables',
                'ordering': ['-last_seen'],
                'unique_together': {('value', 'type')},
            },
        ),
    ]
