# Generated by Django 5.2.1 on 2025-05-21 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observable',
            old_name='malicious',
            new_name='is_malicious',
        ),
    ]
