# Generated by Django 5.2.1 on 2025-05-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_malicious_observable_is_malicious'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='observable',
            unique_together=set(),
        ),
    ]
