# Generated by Django 5.2.1 on 2025-05-21 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250521_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='MitreTactic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tactic_id', models.CharField(max_length=50, unique=True, verbose_name='Tactic ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'MITRE Tactic',
                'verbose_name_plural': 'MITRE Tactics',
                'ordering': ['tactic_id'],
            },
        ),
        migrations.CreateModel(
            name='MitreTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique_id', models.CharField(max_length=50, unique=True, verbose_name='Technique ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('tactics', models.ManyToManyField(related_name='techniques', to='core.mitretactic')),
            ],
            options={
                'verbose_name': 'MITRE Technique',
                'verbose_name_plural': 'MITRE Techniques',
                'ordering': ['technique_id'],
            },
        ),
        migrations.CreateModel(
            name='MitreSubTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_technique_id', models.CharField(max_length=50, unique=True, verbose_name='Sub-technique ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('parent_technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtechniques', to='core.mitretechnique')),
            ],
            options={
                'verbose_name': 'MITRE Sub-technique',
                'verbose_name_plural': 'MITRE Sub-techniques',
                'ordering': ['sub_technique_id'],
            },
        ),
    ]
