# Generated by Django 5.2.1 on 2025-05-21 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Case Created'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('assignee_changed', 'Assignee Changed'), ('due_date_changed', 'Due Date Changed'), ('comment_added', 'Comment Added'), ('attachment_added', 'Attachment Added'), ('alert_linked', 'Alert Linked'), ('alert_unlinked', 'Alert Unlinked'), ('custom', 'Custom Event')], max_length=20, verbose_name='Event Type')),
                ('title', models.CharField(max_length=255, verbose_name='Event Title')),
                ('description', models.TextField(blank=True, verbose_name='Event Description')),
                ('old_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Old Value')),
                ('new_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='New Value')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='cases.case')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Event',
                'verbose_name_plural': 'Case Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
