# Generated by Django 5.2.1 on 2025-05-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_threatcategory_tasktemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Case Created'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('assignee_changed', 'Assignee Changed'), ('due_date_changed', 'Due Date Changed'), ('comment_added', 'Comment Added'), ('attachment_added', 'Attachment Added'), ('alert_linked', 'Alert Linked'), ('alert_unlinked', 'Alert Unlinked'), ('tlp_changed', 'TLP Changed'), ('pap_changed', 'PAP Changed'), ('tags_changed', 'Tags Changed'), ('observable_added', 'Observable Added'), ('observable_removed', 'Observable Removed'), ('task_added', 'Task Added'), ('task_updated', 'Task Updated'), ('task_completed', 'Task Completed'), ('mitre_attack_added', 'MITRE ATT&CK Added'), ('mitre_attack_removed', 'MITRE ATT&CK Removed'), ('threat_intel_added', 'Threat Intelligence Added'), ('custom', 'Custom Event')], max_length=25, verbose_name='Event Type'),
        ),
    ]
