# Generated by Django 5.2.1 on 2025-05-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_pap_case_tlp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Case Created'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('assignee_changed', 'Assignee Changed'), ('due_date_changed', 'Due Date Changed'), ('comment_added', 'Comment Added'), ('attachment_added', 'Attachment Added'), ('alert_linked', 'Alert Linked'), ('alert_unlinked', 'Alert Unlinked'), ('tlp_changed', 'TLP Changed'), ('pap_changed', 'PAP Changed'), ('custom', 'Custom Event')], max_length=20, verbose_name='Event Type'),
        ),
    ]
