# Generated by Django 5.2.1 on 2025-05-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_tags_alter_caseevent_event_type'),
        ('core', '0002_alter_tag_color_alter_tag_name_observable'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='observables',
            field=models.ManyToManyField(blank=True, related_name='cases', to='core.observable', verbose_name='Observables'),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Case Created'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('assignee_changed', 'Assignee Changed'), ('due_date_changed', 'Due Date Changed'), ('comment_added', 'Comment Added'), ('attachment_added', 'Attachment Added'), ('alert_linked', 'Alert Linked'), ('alert_unlinked', 'Alert Unlinked'), ('tlp_changed', 'TLP Changed'), ('pap_changed', 'PAP Changed'), ('tags_changed', 'Tags Changed'), ('observable_added', 'Observable Added'), ('observable_removed', 'Observable Removed'), ('custom', 'Custom Event')], max_length=20, verbose_name='Event Type'),
        ),
    ]
