-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "AuditAction" ADD VALUE 'WORKSPACE_SECURITY_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'DATA_EXPORTED';
ALTER TYPE "AuditAction" ADD VALUE 'SUBSCRIPTION_CANCELLED';
ALTER TYPE "AuditAction" ADD VALUE 'SUBSCRIPTION_DELETED';
ALTER TYPE "AuditAction" ADD VALUE 'FEATURE_USED';
ALTER TYPE "AuditAction" ADD VALUE 'FEATURE_DENIED';
ALTER TYPE "AuditAction" ADD VALUE 'FEATURES_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'ADMIN_ACTION';
ALTER TYPE "AuditAction" ADD VALUE 'ADMIN_SUSPEND_USER';
ALTER TYPE "AuditAction" ADD VALUE 'ADMIN_SUSPEND_WORKSPACE';
ALTER TYPE "AuditAction" ADD VALUE 'ADMIN_RESET_PASSWORD';
ALTER TYPE "AuditAction" ADD VALUE 'ADMIN_DELETE_USER';
ALTER TYPE "AuditAction" ADD VALUE 'ADMIN_UPDATE_QUOTAS';
ALTER TYPE "AuditAction" ADD VALUE 'ADMIN_PROCESS_REFUND';
ALTER TYPE "AuditAction" ADD VALUE 'ADMIN_OVERRIDE_SUBSCRIPTION';
ALTER TYPE "AuditAction" ADD VALUE 'ADMIN_PAUSE_JOB';
ALTER TYPE "AuditAction" ADD VALUE 'ADMIN_RESUME_JOB';
ALTER TYPE "AuditAction" ADD VALUE 'ADMIN_UPDATE_JOB_SCHEDULE';
ALTER TYPE "AuditAction" ADD VALUE 'ADMIN_RETRY_DLQ_JOB';
ALTER TYPE "AuditAction" ADD VALUE 'ADMIN_RESOLVE_DLQ_JOB';
ALTER TYPE "AuditAction" ADD VALUE 'UPDATE_USER_ADMIN_STATUS';
