# Generated by Django 5.2.1 on 2025-05-21 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10, verbose_name='Severity')),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=15, verbose_name='Status')),
                ('tlp', models.CharField(choices=[('white', 'TLP:WHITE'), ('green', 'TLP:GREEN'), ('amber', 'TLP:AMBER'), ('red', 'TLP:RED')], default='amber', help_text='Traffic Light Protocol - Confidentiality of information', max_length=10, verbose_name='TLP')),
                ('pap', models.CharField(choices=[('white', 'PAP:WHITE'), ('green', 'PAP:GREEN'), ('amber', 'PAP:AMBER'), ('red', 'PAP:RED')], default='amber', help_text='Permissible Actions Protocol - Level of exposure of information', max_length=10, verbose_name='PAP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL)),
                ('observables', models.ManyToManyField(blank=True, related_name='alerts', to='core.observable', verbose_name='Observables')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='organizations.organization')),
                ('related_alerts', models.ManyToManyField(blank=True, help_text='Alerts that are related or similar to this one', to='alerts.alert', verbose_name='Related Alerts')),
                ('tags', models.ManyToManyField(blank=True, related_name='alerts', to='core.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='alerts.alert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Comment',
                'verbose_name_plural': 'Alert Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Field Name')),
                ('label', models.CharField(max_length=100, verbose_name='Field Label')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('url', 'URL'), ('select', 'Select')], default='text', max_length=20, verbose_name='Field Type')),
                ('required', models.BooleanField(default=False, verbose_name='Required')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('placeholder', models.CharField(blank=True, max_length=200, verbose_name='Placeholder')),
                ('default_value', models.CharField(blank=True, max_length=200, verbose_name='Default Value')),
                ('options', models.JSONField(blank=True, help_text='Options for select field type (JSON array)', null=True, verbose_name='Options')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_custom_fields', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Alert Custom Field',
                'verbose_name_plural': 'Alert Custom Fields',
                'ordering': ['order'],
                'unique_together': {('name', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Alert Created'), ('status_changed', 'Status Changed'), ('severity_changed', 'Severity Changed'), ('assignee_changed', 'Assignee Changed'), ('tlp_changed', 'TLP Changed'), ('pap_changed', 'PAP Changed'), ('tags_changed', 'Tags Changed'), ('observable_added', 'Observable Added'), ('observable_removed', 'Observable Removed'), ('comment_added', 'Comment Added'), ('related_alert_added', 'Related Alert Added'), ('related_alert_removed', 'Related Alert Removed'), ('escalated', 'Escalated to Case'), ('custom', 'Custom Event')], default='created', max_length=25, verbose_name='Event Type')),
                ('title', models.CharField(max_length=255, verbose_name='Event Title')),
                ('description', models.TextField(blank=True, verbose_name='Event Description')),
                ('old_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Old Value')),
                ('new_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='New Value')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='alerts.alert')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Event',
                'verbose_name_plural': 'Alert Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertCustomValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, verbose_name='Value')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_values', to='alerts.alert')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='alerts.alertcustomfield')),
            ],
            options={
                'verbose_name': 'Alert Custom Value',
                'verbose_name_plural': 'Alert Custom Values',
                'unique_together': {('alert', 'field')},
            },
        ),
    ]
