# Generated by Django 5.2.1 on 2025-05-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='pap',
            field=models.CharField(choices=[('white', 'PAP:WHITE'), ('green', 'PAP:GREEN'), ('amber', 'PAP:AMBER'), ('red', 'PAP:RED')], default='amber', help_text='Permissible Actions Protocol - Level of exposure of information', max_length=10, verbose_name='PAP'),
        ),
        migrations.AddField(
            model_name='alert',
            name='tlp',
            field=models.CharField(choices=[('white', 'TLP:WHITE'), ('green', 'TLP:GREEN'), ('amber', 'TLP:AMBER'), ('red', 'TLP:RED')], default='amber', help_text='Traffic Light Protocol - Confidentiality of information', max_length=10, verbose_name='TLP'),
        ),
    ]
