# Generated by Django 5.2.1 on 2025-05-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('core', '0004_mitretactic_mitretechnique_mitresubtechnique'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='mitre_subtechniques',
            field=models.ManyToManyField(blank=True, related_name='alerts', to='core.mitresubtechnique', verbose_name='MITRE Sub-techniques'),
        ),
        migrations.AddField(
            model_name='alert',
            name='mitre_tactics',
            field=models.ManyToManyField(blank=True, related_name='alerts', to='core.mitretactic', verbose_name='MITRE Tactics'),
        ),
        migrations.AddField(
            model_name='alert',
            name='mitre_techniques',
            field=models.ManyToManyField(blank=True, related_name='alerts', to='core.mitretechnique', verbose_name='MITRE Techniques'),
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Alert Created'), ('status_changed', 'Status Changed'), ('severity_changed', 'Severity Changed'), ('assignee_changed', 'Assignee Changed'), ('tlp_changed', 'TLP Changed'), ('pap_changed', 'PAP Changed'), ('tags_changed', 'Tags Changed'), ('observable_added', 'Observable Added'), ('observable_removed', 'Observable Removed'), ('comment_added', 'Comment Added'), ('related_alert_added', 'Related Alert Added'), ('related_alert_removed', 'Related Alert Removed'), ('escalated', 'Escalated to Case'), ('mitre_attack_added', 'MITRE ATT&CK Added'), ('mitre_attack_removed', 'MITRE ATT&CK Removed'), ('custom', 'Custom Event')], default='created', max_length=25, verbose_name='Event Type'),
        ),
    ]
