# Generated by Django 5.2.1 on 2025-05-21 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_pap_alert_tlp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Alert Created'), ('status_changed', 'Status Changed'), ('severity_changed', 'Severity Changed'), ('assignee_changed', 'Assignee Changed'), ('tlp_changed', 'TLP Changed'), ('pap_changed', 'PAP Changed'), ('escalated', 'Escalated to Case'), ('custom', 'Custom Event')], max_length=20, verbose_name='Event Type')),
                ('title', models.CharField(max_length=255, verbose_name='Event Title')),
                ('description', models.TextField(blank=True, verbose_name='Event Description')),
                ('old_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Old Value')),
                ('new_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='New Value')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='alerts.alert')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Event',
                'verbose_name_plural': 'Alert Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
