# Generated by Django 5.2.1 on 2025-05-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alert_tags_alter_alertevent_event_type'),
        ('core', '0002_alter_tag_color_alter_tag_name_observable'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='observables',
            field=models.ManyToManyField(blank=True, related_name='alerts', to='core.observable', verbose_name='Observables'),
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Alert Created'), ('status_changed', 'Status Changed'), ('severity_changed', 'Severity Changed'), ('assignee_changed', 'Assignee Changed'), ('tlp_changed', 'TLP Changed'), ('pap_changed', 'PAP Changed'), ('tags_changed', 'Tags Changed'), ('observable_added', 'Observable Added'), ('observable_removed', 'Observable Removed'), ('escalated', 'Escalated to Case'), ('custom', 'Custom Event')], max_length=20, verbose_name='Event Type'),
        ),
    ]
